[package]
name = "gwipt"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
git2 = "0.15"
reqwest = { version = "0.11", features = ["json"] }
notify-debouncer-mini = "0.2"
